[project]
name = "WorkflowUIPlugin"
description = "This custom node is a plugin for: WorkflowUI Application, found here: https://github.com/jimpi-dev/WorkflowUI"
version = "1.0.2"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/jimpi-dev/WorkflowUIPlugin"

[tool.comfy]
PublisherId = "jimpi"
DisplayName = "WorkflowUIPlugin"
Icon = "https://raw.githubusercontent.com/jimpi-dev/WorkflowUIPlugin/refs/heads/develop/icon.png"
includes = []
